@startuml
  object ProductionYear{
    TimeID
    Year
  }
  
  object Geografy{
    GeografyID
    Country
    Federal State
  }
  
  object CropProduction{
    CropProductionID
    TimeID
    GeografyID
    CropID
    ---
    Ammound
  }
  
  object Crop{
    CropID
    CropType
  }
  
  CropProduction "*" -up- "1" ProductionYear
  CropProduction "*" -left- "1" Geografy
  CropProduction "*" -right- "1" Crop

@enduml