@startuml
  object ProductionYear{
    TimeID
    Year
  }
  
  object Geografy{
    GeografyID
    Country
  }
  
  object CropProduction{
    CropProductionID
    TimeID
    GeografyID
    ---
    Wheat
    Barley
    Grain Corn inc. CCM
    Potatoes
    Sugarbeet
    Rapeseed and Turnips
    Soybeans
  }
  
  CropProduction "*" -up- "1" ProductionYear
  CropProduction "*" -left- "1" Geografy

@enduml